C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\backends\utils.py, line 105, in _execute
                return self.cursor.execute(sql, params)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\backends\sqlite3\base.py, line 360, in execute
        return super().execute(query, params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
The above exception (no such table: events_event) was the direct cause of the following exception:
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\core\handlers\exception.py, line 55, in inner
                response = get_response(request)
                               ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\core\handlers\base.py, line 220, in _get_response
                response = response.render()
                                ^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\response.py, line 114, in render
            self.content = self.rendered_content
                                ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\response.py, line 92, in rendered_content
        return template.render(context, self._request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\backends\django.py, line 107, in render
            return self.template.render(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\base.py, line 171, in render
                    return self._render(context)
                                ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\base.py, line 163, in _render
        return self.nodelist.render(context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\base.py, line 1016, in render
        return SafeString("".join([node.render_annotated(context) for node in self]))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\base.py, line 977, in render_annotated
            return self.render(context)
                        ^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\loader_tags.py, line 159, in render
            return compiled_parent._render(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\base.py, line 163, in _render
        return self.nodelist.render(context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\base.py, line 1016, in render
        return SafeString("".join([node.render_annotated(context) for node in self]))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\base.py, line 977, in render_annotated
            return self.render(context)
                        ^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\loader_tags.py, line 65, in render
                result = block.nodelist.render(context)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\base.py, line 1016, in render
        return SafeString("".join([node.render_annotated(context) for node in self]))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\base.py, line 977, in render_annotated
            return self.render(context)
                        ^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\template\defaulttags.py, line 326, in render
            if match:
                    ^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\models\query.py, line 398, in __bool__
        self._fetch_all()
             ^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\models\query.py, line 1935, in _fetch_all
            self._result_cache = list(self._iterable_class(self))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\models\query.py, line 91, in __iter__
        results = compiler.execute_sql(
                       …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\models\sql\compiler.py, line 1622, in execute_sql
            else:
                return
        if chunked_fetch:
            cursor = self.connection.chunked_cursor()
        else:
            cursor = self.connection.cursor()
        try:
            cursor.execute(sql, params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        except Exception:
            # Might fail for server-side cursors (e.g. connection closed)
            cursor.close()
            raise
        if result_type == ROW_COUNT:
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\backends\utils.py, line 122, in execute
            return super().execute(sql, params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\backends\utils.py, line 79, in execute
        return self._execute_with_wrappers(
                    …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\backends\utils.py, line 92, in _execute_with_wrappers
        return executor(sql, params, many, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\backends\utils.py, line 100, in _execute
        with self.db.wrap_database_errors:
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\utils.py, line 91, in __exit__
                raise dj_exc_value.with_traceback(traceback) from exc_value
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\backends\utils.py, line 105, in _execute
                return self.cursor.execute(sql, params)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
C:\Users\cnnsy\Desktop\DjangoEventManager\venv\Lib\site-packages\django\db\backends\sqlite3\base.py, line 360, in execute
        return super().execute(query, params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 